/*
  # Seed Specialties and Procedures Data

  1. Sample Data
    - Common medical specialties with descriptions
    - Popular medical procedures with detailed information
    
  2. Purpose
    - Provide initial content for Browse section
    - Enable specialty and procedure pages to function immediately
*/

-- Insert Common Medical Specialties
INSERT INTO specialties_master (name, slug, description, long_description, icon, category, common_conditions, seo_title, seo_description, is_active, display_order) VALUES
('Family Medicine', 'family-medicine', 'Primary care for patients of all ages', 'Family medicine physicians provide comprehensive healthcare for individuals and families across all ages, genders, diseases, and parts of the body. They are trained to treat a broad range of conditions.', '🏥', 'Primary Care', ARRAY['Common colds', 'Flu', 'Diabetes', 'High blood pressure', 'Routine checkups'], 'Find Family Medicine Doctors Near You | Doktochain', 'Book appointments with experienced family medicine physicians. Comprehensive primary care for all ages.', true, 1),

('Dermatology', 'dermatology', 'Skin, hair, and nail care specialists', 'Dermatologists diagnose and treat conditions affecting the skin, hair, and nails. They manage everything from acne and eczema to skin cancer screening and cosmetic procedures.', '💆‍♀️', 'Specialty Care', ARRAY['Acne', 'Eczema', 'Psoriasis', 'Skin cancer', 'Rashes', 'Hair loss'], 'Find Dermatologists Near You | Skin Care Specialists', 'Connect with board-certified dermatologists for skin, hair, and nail concerns. Book online today.', true, 2),

('Cardiology', 'cardiology', 'Heart and cardiovascular system specialists', 'Cardiologists specialize in diagnosing and treating heart and blood vessel conditions. They help manage heart disease, perform cardiac tests, and provide preventive care.', '❤️', 'Specialty Care', ARRAY['Heart disease', 'High blood pressure', 'Chest pain', 'Heart attack', 'Arrhythmia'], 'Find Cardiologists Near You | Heart Specialists', 'Book appointments with experienced cardiologists for heart and cardiovascular care.', true, 3),

('Pediatrics', 'pediatrics', 'Healthcare for infants, children, and adolescents', 'Pediatricians provide medical care for infants, children, and adolescents. They monitor growth and development, provide vaccinations, and treat childhood illnesses.', '👶', 'Primary Care', ARRAY['Well-child visits', 'Vaccinations', 'Common childhood illnesses', 'Growth monitoring', 'Developmental screening'], 'Find Pediatricians Near You | Child Healthcare', 'Connect with pediatricians for your child''s healthcare needs. Schedule appointments online.', true, 4),

('Orthopedics', 'orthopedics', 'Bone, joint, and muscle specialists', 'Orthopedic surgeons diagnose and treat conditions affecting the musculoskeletal system, including bones, joints, ligaments, tendons, and muscles.', '🦴', 'Specialty Care', ARRAY['Fractures', 'Arthritis', 'Sports injuries', 'Back pain', 'Joint replacement'], 'Find Orthopedic Surgeons Near You | Bone & Joint Care', 'Book appointments with orthopedic specialists for bone, joint, and muscle conditions.', true, 5),

('Internal Medicine', 'internal-medicine', 'Adult primary care specialists', 'Internists specialize in the prevention, diagnosis, and treatment of adult diseases. They provide comprehensive care for complex medical conditions.', '🩺', 'Primary Care', ARRAY['Diabetes', 'Hypertension', 'Cholesterol management', 'Chronic disease management', 'Preventive care'], 'Find Internal Medicine Doctors Near You | Adult Care', 'Connect with internal medicine physicians for comprehensive adult healthcare.', true, 6),

('Psychiatry', 'psychiatry', 'Mental health specialists', 'Psychiatrists are medical doctors who specialize in mental health, including diagnosis, treatment, and prevention of mental, emotional, and behavioral disorders.', '🧠', 'Mental Health', ARRAY['Depression', 'Anxiety', 'Bipolar disorder', 'ADHD', 'PTSD', 'Substance abuse'], 'Find Psychiatrists Near You | Mental Health Care', 'Book appointments with licensed psychiatrists for mental health support and treatment.', true, 7),

('Obstetrics & Gynecology', 'obstetrics-gynecology', 'Women''s health specialists', 'OB-GYNs provide healthcare for women, including pregnancy care, reproductive health, and gynecological conditions.', '👩‍⚕️', 'Specialty Care', ARRAY['Pregnancy care', 'Annual exams', 'Birth control', 'Menopause', 'Fertility'], 'Find OB-GYN Doctors Near You | Women''s Health', 'Connect with OB-GYN specialists for comprehensive women''s healthcare needs.', true, 8),

('Endocrinology', 'endocrinology', 'Hormone and metabolism specialists', 'Endocrinologists diagnose and treat hormone imbalances and conditions affecting the endocrine system.', '🦷', 'Specialty Care', ARRAY['Diabetes', 'Thyroid disorders', 'Osteoporosis', 'Hormone imbalances', 'Metabolic disorders'], 'Find Endocrinologists Near You | Hormone Specialists', 'Book appointments with endocrinology specialists for hormone-related conditions.', true, 9),

('Ophthalmology', 'ophthalmology', 'Eye care and vision specialists', 'Ophthalmologists are medical doctors who specialize in eye and vision care, including surgery.', '👁️', 'Specialty Care', ARRAY['Cataracts', 'Glaucoma', 'Vision problems', 'Eye infections', 'LASIK surgery'], 'Find Ophthalmologists Near You | Eye Care Specialists', 'Connect with eye care specialists for comprehensive vision and eye health services.', true, 10)

ON CONFLICT (slug) DO NOTHING;

-- Insert Common Medical Procedures
INSERT INTO procedures_master (name, slug, cpt_code, description, long_description, category, preparation_info, recovery_info, average_duration_minutes, what_to_expect, typical_cost_min, typical_cost_max, is_active, is_common, display_order, seo_title, seo_description) VALUES
('Annual Physical Exam', 'annual-physical-exam', '99395', 'Comprehensive health checkup', 'An annual physical exam is a routine checkup to assess your overall health, screen for diseases, and update preventive care measures. Your doctor will review your medical history, perform a physical examination, and order any necessary tests.', 'Preventive Care', 'Fast for 8-12 hours before appointment if blood work is needed. Bring list of current medications.', 'No recovery time needed. Results typically available within 1-2 weeks.', 45, 'Your doctor will check vital signs, perform a physical examination, discuss health concerns, and may order blood tests or other screenings.', 150.00, 300.00, true, true, 1, 'Annual Physical Exam Near You | Book Online', 'Schedule your annual physical examination with qualified healthcare providers. Preventive care covered by most insurance.'),

('Skin Cancer Screening', 'skin-cancer-screening', '99203', 'Full-body skin examination', 'A skin cancer screening involves a thorough examination of your skin to identify suspicious moles or lesions that could be cancerous. Early detection is key to successful treatment.', 'Screening', 'No special preparation needed. Remove makeup and nail polish if possible.', 'No recovery time. Biopsy results, if needed, available within 1-2 weeks.', 20, 'Your dermatologist will examine your entire body, photograph suspicious areas, and may perform a biopsy if needed.', 100.00, 250.00, true, true, 2, 'Skin Cancer Screening Near You | Dermatology', 'Get screened for skin cancer by board-certified dermatologists. Early detection saves lives.'),

('Echocardiogram', 'echocardiogram', '93306', 'Ultrasound of the heart', 'An echocardiogram uses sound waves to create detailed images of your heart structure and function. It helps diagnose heart conditions and assess heart valve function.', 'Diagnostic', 'No special preparation needed. Wear comfortable clothing.', 'No recovery time. Resume normal activities immediately.', 60, 'A technician will apply gel to your chest and use a transducer to capture images of your heart. The procedure is painless.', 300.00, 800.00, true, true, 3, 'Echocardiogram Near You | Heart Ultrasound', 'Book an echocardiogram with experienced cardiac specialists. Fast results and insurance accepted.'),

('Telehealth Consultation', 'telehealth-consultation', '99213', 'Virtual doctor visit', 'A telehealth consultation allows you to see a doctor via video call from the comfort of your home. Perfect for minor illnesses, prescription refills, and follow-up appointments.', 'Telemedicine', 'Test your internet connection and camera. Have your insurance card and list of medications ready.', 'No recovery needed.', 15, 'Connect with your doctor via secure video call to discuss symptoms, receive diagnosis, and get prescriptions if needed.', 50.00, 150.00, true, true, 4, 'Telehealth Consultation | Virtual Doctor Visit', 'See a doctor online through secure video consultation. No travel required. Same-day appointments available.'),

('X-Ray', 'x-ray', '73610', 'Diagnostic imaging', 'An X-ray uses electromagnetic radiation to create images of bones and internal structures. Commonly used to diagnose fractures, infections, and other conditions.', 'Imaging', 'Remove jewelry and metal objects. Inform technician if pregnant.', 'No recovery time. Resume normal activities immediately.', 15, 'A technician will position you and take images. You may need to hold still or hold your breath briefly.', 100.00, 300.00, true, true, 5, 'X-Ray Imaging Near You | Fast Results', 'Get X-ray imaging from certified radiologists. Walk-ins welcome. Results available quickly.'),

('Blood Pressure Check', 'blood-pressure-check', '99000', 'Hypertension screening', 'A simple test to measure the force of blood against artery walls. Regular monitoring helps prevent heart disease and stroke.', 'Screening', 'Avoid caffeine 30 minutes before test. Sit quietly for 5 minutes before measurement.', 'No recovery needed.', 5, 'A cuff will be placed on your arm and inflated to measure your blood pressure. The procedure is quick and painless.', 0.00, 25.00, true, true, 6, 'Blood Pressure Check Near You | Free Screening', 'Get your blood pressure checked at any of our locations. Walk-ins welcome. Most insurance plans cover.'),

('Vaccination', 'vaccination', '90471', 'Immunization services', 'Protect yourself and others from preventable diseases through vaccination. We offer flu shots, COVID-19 vaccines, and other routine immunizations.', 'Preventive Care', 'Inform provider of any allergies. Wear short sleeves for easy access.', 'Wait 15 minutes after vaccination. Minor soreness at injection site is normal.', 10, 'Receive your vaccine injection. Healthcare provider will monitor you briefly for any reactions.', 25.00, 150.00, true, true, 7, 'Vaccinations Near You | Flu Shots & More', 'Get vaccinated at convenient locations. Walk-ins and appointments available. Insurance accepted.'),

('Joint Injection', 'joint-injection', '20610', 'Pain relief for arthritis', 'Corticosteroid injections can reduce inflammation and relieve pain in joints affected by arthritis or injury.', 'Pain Management', 'No special preparation. Inform doctor of blood thinners.', 'Rest joint for 24 hours. Some soreness is normal. Benefits appear in 3-5 days.', 20, 'Doctor will clean the injection site and inject medication directly into the affected joint using ultrasound guidance.', 200.00, 600.00, true, true, 8, 'Joint Injection Near You | Arthritis Pain Relief', 'Get relief from joint pain with corticosteroid injections. Experienced providers. Insurance accepted.')

ON CONFLICT (slug) DO NOTHING;
